<a href="https://colab.research.google.com/github/cflores23/optimizacion/blob/Simplex-method/Simplex_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
gamma=1.5
betha=0.5
ephsilon=0.003
evaluations_dict={}

In [ ]:
p_1=np.array((0,0))
p_2=np.array((2,0))
p_3=np.array((1,1))

In [ ]:
def evaluate_function(x_1,x_2):
  result=((x_1**2)+x_2-11)**2+(x_1+(x_2**2)-7)**2
  return result

In [ ]:
x_1=evaluate_function(0,0)
evaluations_dict['p_1']=x_1
evaluations_dict

{'p_1': 170}

In [ ]:
x_2=evaluate_function(2,0)
evaluations_dict['p_2']=x_2
evaluations_dict

{'p_1': 170, 'p_2': 74}

In [ ]:
x_3=evaluate_function(1,1)
evaluations_dict['p_3']=x_3
evaluations_dict

{'p_1': 170, 'p_2': 74, 'p_3': 106}

In [ ]:
sortedDict = sorted(evaluations_dict.items(), key=lambda x: x[1])
sortedDict

[('p_2', 74), ('p_3', 106), ('p_1', 170)]

In [ ]:
#print(next(iter(sortedDict)))
best=sortedDict[0][0]
if best == 'p_2':
  best = p_2
if best == 'p_1':
  best = p_1
if best == 'p_3':
  best = p_3
best

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  import sys


array([2, 0])

In [ ]:
worst=sortedDict[2][0]
if worst == 'p_2':
  worst = p_2
if worst == 'p_1':
  worst = p_1
if worst == 'p_3':
  worst = p_3
worst

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  


array([0, 0])

In [ ]:
second_worst=sortedDict[1][0]
if second_worst == 'p_2':
  second_worst = p_2
if second_worst == 'p_1':
  second_worst = p_1
if second_worst == 'p_3':
  second_worst = p_3
second_worst

array([1, 1])

Cálculo del centroide

In [ ]:
x_c = (best+second_worst)/2
x_c

array([1.5, 0.5])

Calcular el punto reflejado:

In [ ]:
x_r = 2*(x_c)-worst
x_r

array([3., 1.])

In [ ]:
fDeX_r = evaluate_function_vector(x_r)
fDeX_r

10.0

Obtener nuevo punto

In [ ]:
x_l = sortedDict[0][1]
x_g = sortedDict[1][1]
x_h = sortedDict[2][1]
x_l

74

In [ ]:
if fDeX_r < x_l:
  x_new = (1+gamma)*x_c - (gamma*worst)
if fDeX_r >= x_h:
  x_new = (1-betha)*x_c + (betha*worst)
if x_g < fDeX_r < x_h:
  x_new = (1+betha)*x_c - (betha*worst)

x_new

array([3.75, 1.25])

In [ ]:
fDeX_new = evaluate_function_vector(x_new)
fDeX_new

21.4453125

Calcular la condición de paro

In [ ]:
#fDeX_i = evaluate_function_vector(best)
#fDeX_i
fDeC = evaluate_function_vector(x_c)
fDeC

95.625

In [ ]:
c_paro = np.sqrt((((fDeX_new-fDeC)**2)/3)+(((x_2-fDeC)**2)/3))
#condition = np.sqrt((((x_1-fDeC)**2)/3)+(((x_2-fDeC)**2)/3))
#condition

##Esta es la implementación iterativa

In [ ]:
import numpy as np

In [ ]:
def evaluate_function_vector(punto):
  result=((punto[0]**2)+punto[1]-11)**2+(punto[0]+(punto[1]**2)-7)**2
  return result

In [ ]:
gamma=1.5
betha=0.5
ephsilon=40
evaluations_dict={}

In [ ]:
q = ephsilon
iteration = 1
p_1=np.array((0,0))
p_2=np.array((2,0))
p_3=np.array((1,1))
while q >= ephsilon:
  print("Iteración "+str(iteration)+"*********************************************")
  x_1=evaluate_function_vector(p_1)
  evaluations_dict['p_1']=x_1
  x_2=evaluate_function_vector(p_2)
  evaluations_dict['p_2']=x_2
  x_3=evaluate_function_vector(p_3)
  evaluations_dict['p_3']=x_3
  sortedDict = sorted(evaluations_dict.items(), key=lambda x: x[1])
  print(sortedDict)
  best=sortedDict[0][0]
  if best == 'p_2':
    best = p_2
  if best == 'p_1':
    best = p_1
  if best == 'p_3':
    best = p_3
  print("Mejor "+str(best))
  worst=sortedDict[2][0]
  if worst == 'p_2':
    worst = p_2
  if worst == 'p_1':
    worst = p_1
  if worst == 'p_3':
    worst = p_3
  print("Peor "+str(worst))
  second_worst=sortedDict[1][0]
  if second_worst == 'p_2':
    second_worst = p_2
  if second_worst == 'p_1':
    second_worst = p_1
  if second_worst == 'p_3':
    second_worst = p_3
  print("Segundo Peor "+str(second_worst))
  x_c = (best+second_worst)/2
  print("Centroide "+str(x_c))
  x_r = 2*(x_c)-worst
  print("x_r "+str(x_r))
  fDeX_r = evaluate_function_vector(x_r)
  print("fDeX_r "+str(fDeX_r))
  x_l = sortedDict[0][1]
  x_g = sortedDict[1][1]
  x_h = sortedDict[2][1]
  x_l
  if fDeX_r < x_l:
    x_new = (1+gamma)*x_c - (gamma*worst)
  if fDeX_r >= x_h:
    x_new = (1-betha)*x_c + (betha*worst)
  if x_g < fDeX_r < x_h:
    x_new = (1+betha)*x_c - (betha*worst)
  fDeX_new = evaluate_function_vector(x_new)
  fDeX_new
  fDeC = evaluate_function_vector(x_c)
  print("fDeC "+str(fDeC))
  q = np.sqrt((((x_1-fDeC)**2)/3)+(((x_2-fDeC)**2)/3)+(((x_3-fDeC)**2)/3))
  p_1 = x_new
  p_2 = best
  p_3 = second_worst
  iteration = iteration+1
  print("X_new "+str(x_new))
  print(q)

print("Mejor solución "+str(x_new)+ "Valor de la función en este punto "+str(fDeX_new))

Iteración 1*********************************************
[('p_2', 74), ('p_3', 106), ('p_1', 170)]
Mejor [2 0]
Peor [0 0]
Segundo Peor [1 1]
Centroide [1.5 0.5]
x_r [3. 1.]
fDeX_r 10.0
fDeC 95.625
X_new [3.75 1.25]
45.11807426076605
Iteración 2*********************************************
[('p_1', 21.4453125), ('p_2', 74), ('p_3', 106)]
Mejor [3.75 1.25]
Peor [1 1]
Segundo Peor [2 0]
Centroide [2.875 0.625]
x_r [4.75 0.25]
fDeX_r 144.3203125
fDeC 18.39501953125
X_new [1.9375 0.8125]
59.932881189586695
Iteración 3*********************************************
[('p_2', 21.4453125), ('p_1', 60.771759033203125), ('p_3', 74)]
Mejor [3.75 1.25]
Peor [2 0]
Segundo Peor [1.9375 0.8125]
Centroide [2.84375 1.03125]
x_r [3.6875 2.0625]
fDeX_r 22.603302001953125
fDeC 13.10655403137207
X_new [1.9375 0.8125]
44.9055246140862
Iteración 4*********************************************
[('p_2', 21.4453125), ('p_1', 60.771759033203125), ('p_3', 60.771759033203125)]
Mejor [3.75 1.25]
Peor [1.9375 0.8125]
Se

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


##Implementación mejorada

In [ ]:
import numpy as np
import math
import random

In [ ]:
def f(X):
    result=((X[0]**2)+X[1]-11)**2 + (X[0]+(X[1]**2)-7)**2
    return result

In [ ]:
def McCormick(x):
  x_1 = x[0]
  x_2 = x[1] 
  res = math.sin(x_1 + x_2) + (x_1 - x_2)**2 - (1.5*x_1) + 2.5 * x_2 + 1
  return res

In [ ]:
def bukin(x):
  x_1 = x[0]
  x_2 = x[1] 
  res = 100 * math.sqrt(abs(x_2 - 0.01*(x_1)**2)) + 0.01 * abs(x_1 + 10)
  return res

In [ ]:
#Simplex inicial
C = 2
x = np.random.randint(10,size=(3))
print(x)
for i in range(1,50):
  indice = random.randint(1, 2)
  x[indice] = x[indice]*(-1)
print(x)
delta = (math.sqrt(N+1)-2)/N-3
x_1 = x[0]+C*delta
x_2 = x[1]+C*delta
x_3 = x[2]+C*delta
X = np.array([[x[0],x_1,-1.0],[x[1],x_2,-1.0],[x[2],x_3,-1.0]])
print(X)

[9 4 5]
[ 9 -4  5]
[[  9.           2.73205081  -1.        ]
 [ -4.         -10.26794919  -1.        ]
 [  5.          -1.26794919  -1.        ]]


In [ ]:
gamma=1.5
beta=0.8
#criterio de terminación
eps=0.003
#número de variables
N = 2

In [ ]:

#Punto inicial (0,0)
histMejor=[]
histQ=[]
#Simplex inicial la tercera columna es almacena el valor de la función objetivo
X = np.array([[-11.0,-9.0,-1.0],[-10.0,-9.0,-1.0],[-8.0,-7.0,-1.0]])

#Evaluar simplex
for i in range(N+1):
        X[i][N]=bukin(X[i]) #el último elemento de la fila toma el valor de f(X)
        
#Ordena el Simplex basado en el último elemento f(X) de menor a mayor
X = X[X[:, N].argsort()]

#contador de iteraciones
k = 1
#mide la distancia del simplex con respecto al centroide
Q = 50

while Q >= eps:
    print("*************** Iteración "+str(k)+"***************************")
        
    print(">>Simplex actual")
    print(X)
    
    fxl = X[0][N]   #el mejor esta en la posición cero
    fxg = X[N-1][N] #el segundo peor está en la posición n-1
    fxh = X[N][N]   #el peor está en la posición n
    
    xl = X[0][0:N]   # obtengo el mejor
    xg = X[N-1][0:N] # obtengo el segundo peor
    xh = X[N][0:N]   # obtengo el peor
    
    #Calcula centroide
    xc = (xl+xg)/N
    fxc = bukin(xc)
    print("xc "+str(xc)+" --> "+str(fxc))

    #Calcula el punto de reflección
    xr = 2*xc-xh
    fxr = bukin(xr)
    print("xr "+str(xr)+" --> "+str(fxr))
    
    #Asigna el valor de la reflección a x_new
    x_new = xr
    
    if fxr < fxl:
        x_new = (1+gamma)*xc - (gamma*xh) #expansión
    elif fxr >= fxh:
        x_new = (1-beta)*xc + (beta*xh) #contracción
    elif fxg < fxr < fxh:
        x_new = (1+beta)*xc - (beta*xh) #contracción
    
    fx_new = bukin(x_new)
    print("x_new "+str(x_new)+" --->"+str(fx_new))
   
    #Reemplazar el peor del simplex
    for j in range(N):
        X[N][j] = x_new[j]
    X[N][N] = fx_new
    
    #incrementa el contador de iteraciones
    k = k+1
    
    #Calcular el valor de Q
    suma = 0
    for i in range(N+1):
        suma += ((X[i][N]-fxc)**2)/(N+1)
    Q = np.sqrt(suma)
    
    print("Q = "+str(Q))
    
    #ordena el simplex actual de acuerdo al valor de la función objetivo
    X = X[X[:, N].argsort()] 
    
    histMejor.append([k,X[0][N]])
    histQ.append([k,Q])

#FIN DEL ALGORITMO 
print("***************************************************************")
print("\n>>FIN DEL ALGORITMO<<")
print("\nMejor solución encontrada\n"+str(X[0][0:N])+" --> "+str(X[0][N])+"\n")

*************** Iteración 1***************************
>>Simplex actual
[[ -8.          -7.         276.42549922]
 [-10.          -9.         316.22776602]
 [-11.          -9.         319.54090617]]
xc [-9. -8.] --> 296.8264415931166
xr [-7. -7.] --> 273.70864366808013
x_new [-6.  -6.5] --->261.9560170741759
Q = 25.875060999395302
*************** Iteración 2***************************
>>Simplex actual
[[ -6.          -6.5        261.95601707]
 [ -8.          -7.         276.42549922]
 [-10.          -9.         316.22776602]]
xc [-7.   -6.75] --> 269.1024809414742
xr [-4.  -4.5] --> 215.93033144922904
x_new [-2.5   -3.375] --->185.47996217739157
Q = 48.63957300726966
*************** Iteración 3***************************
>>Simplex actual
[[ -2.5         -3.375      185.47996218]
 [ -6.          -6.5        261.95601707]
 [ -8.          -7.         276.42549922]]
xc [-4.25   -4.9375] --> 226.29023414782398
xr [-0.5   -2.875] --> 169.72695453687373
x_new [ 1.375   -1.84375] --->136.59291