<a href="https://colab.research.google.com/github/cflores23/optimizacion/blob/Simplex-method/Simplex_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
gamma=1.5
betha=0.5
ephsilon=0.003
evaluations_dict={}

In [ ]:
p_1=np.array((0,0))
p_2=np.array((2,0))
p_3=np.array((1,1))

In [ ]:
def evaluate_function(x_1,x_2):
  result=((x_1**2)+x_2-11)**2+(x_1+(x_2**2)-7)**2
  return result

In [ ]:
x_1=evaluate_function(0,0)
evaluations_dict['p_1']=x_1
evaluations_dict

{'p_1': 170}

In [ ]:
x_2=evaluate_function(2,0)
evaluations_dict['p_2']=x_2
evaluations_dict

{'p_1': 170, 'p_2': 74}

In [ ]:
x_3=evaluate_function(1,1)
evaluations_dict['p_3']=x_3
evaluations_dict

{'p_1': 170, 'p_2': 74, 'p_3': 106}

In [ ]:
sortedDict = sorted(evaluations_dict.items(), key=lambda x: x[1])
sortedDict

[('p_2', 74), ('p_3', 106), ('p_1', 170)]

In [ ]:
#print(next(iter(sortedDict)))
best=sortedDict[0][0]
if best == 'p_2':
  best = p_2
if best == 'p_1':
  best = p_1
if best == 'p_3':
  best = p_3
best

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  import sys


array([2, 0])

In [ ]:
worst=sortedDict[2][0]
if worst == 'p_2':
  worst = p_2
if worst == 'p_1':
  worst = p_1
if worst == 'p_3':
  worst = p_3
worst

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  


array([0, 0])

In [ ]:
second_worst=sortedDict[1][0]
if second_worst == 'p_2':
  second_worst = p_2
if second_worst == 'p_1':
  second_worst = p_1
if second_worst == 'p_3':
  second_worst = p_3
second_worst

array([1, 1])

Cálculo del centroide

In [ ]:
x_c = (best+second_worst)/2
x_c

array([1.5, 0.5])

Calcular el punto reflejado:

In [ ]:
x_r = 2*(x_c)-worst
x_r

array([3., 1.])

In [ ]:
fDeX_r = evaluate_function_vector(x_r)
fDeX_r

10.0

Obtener nuevo punto

In [ ]:
x_l = sortedDict[0][1]
x_g = sortedDict[1][1]
x_h = sortedDict[2][1]
x_l

74

In [ ]:
if fDeX_r < x_l:
  x_new = (1+gamma)*x_c - (gamma*worst)
if fDeX_r >= x_h:
  x_new = (1-betha)*x_c + (betha*worst)
if x_g < fDeX_r < x_h:
  x_new = (1+betha)*x_c - (betha*worst)

x_new

array([3.75, 1.25])

In [ ]:
fDeX_new = evaluate_function_vector(x_new)
fDeX_new

21.4453125

Calcular la condición de paro

In [ ]:
#fDeX_i = evaluate_function_vector(best)
#fDeX_i
fDeC = evaluate_function_vector(x_c)
fDeC

95.625

In [ ]:
c_paro = np.sqrt((((fDeX_new-fDeC)**2)/3)+(((x_2-fDeC)**2)/3))
#condition = np.sqrt((((x_1-fDeC)**2)/3)+(((x_2-fDeC)**2)/3))
#condition

##Esta es la implementación iterativa

In [16]:
import numpy as np

In [17]:
def evaluate_function_vector(punto):
  result=((punto[0]**2)+punto[1]-11)**2+(punto[0]+(punto[1]**2)-7)**2
  return result

In [22]:
gamma=1.5
betha=0.5
ephsilon=40
evaluations_dict={}

In [23]:
q = ephsilon
iteration = 1
p_1=np.array((0,0))
p_2=np.array((2,0))
p_3=np.array((1,1))
while q >= ephsilon:
  print("Iteración "+str(iteration)+"*********************************************")
  x_1=evaluate_function_vector(p_1)
  evaluations_dict['p_1']=x_1
  x_2=evaluate_function_vector(p_2)
  evaluations_dict['p_2']=x_2
  x_3=evaluate_function_vector(p_3)
  evaluations_dict['p_3']=x_3
  sortedDict = sorted(evaluations_dict.items(), key=lambda x: x[1])
  print(sortedDict)
  best=sortedDict[0][0]
  if best == 'p_2':
    best = p_2
  if best == 'p_1':
    best = p_1
  if best == 'p_3':
    best = p_3
  print("Mejor "+str(best))
  worst=sortedDict[2][0]
  if worst == 'p_2':
    worst = p_2
  if worst == 'p_1':
    worst = p_1
  if worst == 'p_3':
    worst = p_3
  print("Peor "+str(worst))
  second_worst=sortedDict[1][0]
  if second_worst == 'p_2':
    second_worst = p_2
  if second_worst == 'p_1':
    second_worst = p_1
  if second_worst == 'p_3':
    second_worst = p_3
  print("Segundo Peor "+str(second_worst))
  x_c = (best+second_worst)/2
  print("Centroide "+str(x_c))
  x_r = 2*(x_c)-worst
  print("x_r "+str(x_r))
  fDeX_r = evaluate_function_vector(x_r)
  print("fDeX_r "+str(fDeX_r))
  x_l = sortedDict[0][1]
  x_g = sortedDict[1][1]
  x_h = sortedDict[2][1]
  x_l
  if fDeX_r < x_l:
    x_new = (1+gamma)*x_c - (gamma*worst)
  if fDeX_r >= x_h:
    x_new = (1-betha)*x_c + (betha*worst)
  if x_g < fDeX_r < x_h:
    x_new = (1+betha)*x_c - (betha*worst)
  fDeX_new = evaluate_function_vector(x_new)
  fDeX_new
  fDeC = evaluate_function_vector(x_c)
  print("fDeC "+str(fDeC))
  q = np.sqrt((((x_1-fDeC)**2)/3)+(((x_2-fDeC)**2)/3)+(((x_3-fDeC)**2)/3))
  p_1 = x_new
  p_2 = best
  p_3 = second_worst
  iteration = iteration+1
  print("X_new "+str(x_new))
  print(q)

print("Mejor solución "+str(x_new)+ "Valor de la función en este punto "+str(fDeX_new))

Iteración 1*********************************************
[('p_2', 74), ('p_3', 106), ('p_1', 170)]
Mejor [2 0]
Peor [0 0]
Segundo Peor [1 1]
Centroide [1.5 0.5]
x_r [3. 1.]
fDeX_r 10.0
fDeC 95.625
X_new [3.75 1.25]
45.11807426076605
Iteración 2*********************************************
[('p_1', 21.4453125), ('p_2', 74), ('p_3', 106)]
Mejor [3.75 1.25]
Peor [1 1]
Segundo Peor [2 0]
Centroide [2.875 0.625]
x_r [4.75 0.25]
fDeX_r 144.3203125
fDeC 18.39501953125
X_new [1.9375 0.8125]
59.932881189586695
Iteración 3*********************************************
[('p_2', 21.4453125), ('p_1', 60.771759033203125), ('p_3', 74)]
Mejor [3.75 1.25]
Peor [2 0]
Segundo Peor [1.9375 0.8125]
Centroide [2.84375 1.03125]
x_r [3.6875 2.0625]
fDeX_r 22.603302001953125
fDeC 13.10655403137207
X_new [1.9375 0.8125]
44.9055246140862
Iteración 4*********************************************
[('p_2', 21.4453125), ('p_1', 60.771759033203125), ('p_3', 60.771759033203125)]
Mejor [3.75 1.25]
Peor [1.9375 0.8125]
Se

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
